AWSTemplateFormatVersion: '2010-09-09'
Description: EC2, ALB, Launch Template, and Auto Scaling Group setup with NGINX

Parameters:
  VPCID:
    Type: String
  PublicSubnet1:
    Type: String
  PublicSubnet2:
    Type: String
  PrivateSubnet1:
    Type: String
  PrivateSubnet2:
    Type: String
  ALBSG:
    Type: String
  WebSG:
    Type: String

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: DemoAppALB
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref ALBSG

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: DemoAppTG
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPCID
      TargetType: instance
      HealthCheckPath: /

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: WebAppTemplate
      LaunchTemplateData:
        ImageId: ami-0d0ad8bb301edb745  # Amazon Linux 2023 x86
        InstanceType: t3.micro
        SecurityGroupIds:
          - !Ref WebSG
        KeyName: shoplyst-project-key
        IamInstanceProfile:
          Name: !ImportValue EC2InstanceProfile
        UserData:
          Fn::Base64: |
            #!/bin/bash
            yum update -y
            amazon-linux-extras install nginx1 -y
            systemctl start nginx
            systemctl enable nginx
            echo "<h1>Deployed via CloudFormation</h1>" > /usr/share/nginx/html/index.html

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: '1'
      MaxSize: '2'
      DesiredCapacity: '1'
      TargetGroupARNs:
        - !Ref TargetGroup

Outputs:
  ALBDNSName:
    Description: DNS name of the Load Balancer
    Value: !GetAtt ALB.DNSName
