AWSTemplateFormatVersion: '2010-09-09'
Description: Master CloudFormation template to deploy web application infrastructure using nested stacks

Parameters:
  VpcTemplateUrl:
    Type: String
    Description: S3 URL for vpc.yaml
  SecurityTemplateUrl:
    Type: String
    Description: S3 URL for security.yaml
  ComputeTemplateUrl:
    Type: String
    Description: S3 URL for compute.yaml
  RdsTemplateUrl:
    Type: String
    Description: S3 URL for rds.yaml

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref VpcTemplateUrl

  SecurityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref SecurityTemplateUrl
      Parameters:
        VPCID: !GetAtt VPCStack.Outputs.VPCID

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref ComputeTemplateUrl
      Parameters:
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        ALBSG: !GetAtt SecurityStack.Outputs.ALBSecurityGroup
        WebSG: !GetAtt SecurityStack.Outputs.WebSecurityGroup

  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref RdsTemplateUrl
      Parameters:
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        DBSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        DBSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        DBSecurityGroup: !GetAtt SecurityStack.Outputs.DBSecurityGroup