AWSTemplateFormatVersion: '2010-09-09'
Description: RDS MySQL Database with Secrets Manager for credentials

Parameters:
  DBSubnet1:
    Type: String
  DBSubnet2:
    Type: String
  VPCID:
    Type: String
  DBSecurityGroup:
    Type: String

Resources:

  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: my-rds-secret
      Description: RDS credentials for MySQL
      SecretString: !Sub |
        {
          "username": "admin",
          "password": "Admin@123456"
        }

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: RDS subnet group
      SubnetIds:
        - !Ref DBSubnet1
        - !Ref DBSubnet2

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: my-db-instance
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      Engine: mysql
      DBName: shopalystdb
      MasterUsername: "admin"
      MasterUserPassword: "Admin@123456"
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: true
      PubliclyAccessible: false

Outputs:
  DBEndpoint:
    Description: RDS endpoint
    Value: !GetAtt RDSInstance.Endpoint.Address
