AWSTemplateFormatVersion: '2010-09-09'
Description: RDS MySQL Database with Secrets Manager for credentials

Parameters:
  VPCID:
    Type: String
  PrivateSubnet1:
    Type: String
  PrivateSubnet2:
    Type: String
  DBSG:
    Type: String

Resources:

  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: my-rds-secret
      Description: RDS credentials for MySQL
      SecretString: !Sub |
        {
          "username": "admin",
          "password": "Admin@123456"
        }

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: RDS subnet group
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: my-db-instance
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      Engine: mysql
      DBName: mydatabase
      MasterUsername: !Sub '{{resolve:secretsmanager:${DBSecret}::username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DBSecret}::password}}'
      VPCSecurityGroups:
        - !Ref DBSecurityGroupId
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: true
      PubliclyAccessible: false

Outputs:
  DBEndpoint:
    Description: RDS endpoint
    Value: !GetAtt RDSInstance.Endpoint.Address
