AWSTemplateFormatVersion: '2010-09-09'
Description: RDS MySQL Database with Secrets Manager for credentials

Parameters:
  DBSubnet1:
    Type: AWS::EC2::Subnet::Id
  DBSubnet2:
    Type: AWS::EC2::Subnet::Id
  VPC:
    Type: AWS::EC2::VPC::Id
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id

Resources:

  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: my-rds-secret
      Description: RDS credentials for MySQL
      SecretString: !Sub |
        {
          "username": "admin",
          "password": "Admin@123456"
        }

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: RDS subnet group
      SubnetIds:
        - !Ref DBSubnet1
        - !Ref DBSubnet2

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: my-db-instance
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      Engine: mysql
      DBName: shopalystdb
      MasterUsername: !Sub '{{resolve:secretsmanager:${DBSecret}::username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DBSecret}::password}}'
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: true
      PubliclyAccessible: false

Outputs:
  DBEndpoint:
    Description: RDS endpoint
    Value: !GetAtt RDSInstance.Endpoint.Address
