AWSTemplateFormatVersion: '2010-09-09'
Description: Master CloudFormation template to deploy web application infrastructure using nested stacks

Parameters:
  VpcTemplateUrl:
    Type: String
    Description: S3 URL for vpc.yaml
  SecurityTemplateUrl:
    Type: String
    Description: S3 URL for security.yaml
  ComputeTemplateUrl:
    Type: String
    Description: S3 URL for compute.yaml
  RdsTemplateUrl:
    Type: String
    Description: S3 URL for rds.yaml
  VpcCIDR:
    Type: String
    Description: VPC CIDR Range
  PublicSubnet1CIDR:
    Type: String
    Description: CIDR Range for Public Subnet
  PublicSubnet2CIDR:
    Type: String
    Description: CIDR Range for Public Subnet
  PrivateSubnet1CIDR:
    Type: String
    Description: CIDR Range for Private Subnet
  PrivateSubnet2CIDR:
    Type: String
    Description: CIDR Range for Private Subnet
  DBUsername:
    Type: String
    Description: RDS Master username
  DBPassword:
    Type: String
    Description: RDS Master password, please don't share with anyone
  KeyName:
    Type: String
    Description: Keypair name for Webapp ec2
  S3BucketName:
    Type: String
    Description: S3 Bucket Name for CICD operation
  DBBootstrap:
    Type: String
  WebBootstrap:
    Type: String
  Email:
    Type: String
    Description: Email address to get Notification on ASG
    

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref VpcTemplateUrl
      Parameters:
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
        
  SecurityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref SecurityTemplateUrl
      Parameters:
        VPCID: !GetAtt VPCStack.Outputs.VPCID

  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref RdsTemplateUrl
      Parameters:
        DBUsername: !Ref DBUsername
        DBPassword: !Ref DBPassword
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        DBSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        DBSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        DBSecurityGroup: !GetAtt SecurityStack.Outputs.DBSecurityGroup

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref ComputeTemplateUrl
      Parameters:
        KeyName: !Ref KeyName
        VPCID: !GetAtt VPCStack.Outputs.VPCID
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        ALBSG: !GetAtt SecurityStack.Outputs.ALBSecurityGroup
        WebSG: !GetAtt SecurityStack.Outputs.WebSecurityGroup
        DBSecretArn: !GetAtt RDSStack.Outputs.DBSecretArn
        DBEndpoint: !GetAtt RDSStack.Outputs.DBEndpoint
        DBBootstrap: !Ref DBBootstrap
        WebBootstrap: !Ref WebBootstrap
        Email: !Ref Email
        S3BucketName: !Ref S3BucketName
